### ISSUE TITLE
Unlocking every module automatically

### ISSUE THREAD

**Issue by abendplays** [normyx/MMM-Facial-Recognition-OCV3#1]
Hi, 
great Tutorial! Unfortunatly, the module is unlocking every module automatically! The recognition (when I try it with tools.facerecognition.py gives me weak:User1) seems to work.. 
Down you can see my config, where I tried to unlock my news Feed as a test, but it is unlocked from the beginning.. Any guesses? 
Thank you!

[config.zip](https://github.com/normyx/MMM-Facial-Recognition-OCV3/files/1713850/config.zip)

**Comment by abendplays** [comment]
Update: 
I got it working with the tools.faceregocnition.py, so it recognizes me by name (Nik). 
But the Mirror ist still unlocking every module from the beginning on, even when the picame is concealed.. 
Any ideas?

**Comment by normyx** [comment]
Hi abendplays,
It seems that you set a wrong name of module. It has to be MMM-Facial-Recognition-OC3 in your config.js, not MMM-Facial-Recognition. The issue was in my doc, I corrected it.
Thx for this
