### ISSUE TITLE
How to modify in config.js

### ISSUE THREAD

**Issue by dennis100kr** [normyx/MMM-Facial-Recognition-OCV3#10]
I got some config syntax error when I change some config.js to setup in other module.
I already done training and test.
                {
                        module: "calendar",
                        header: "SCHEDULE",
                        position: "top_left",
                        config: {
                                calendars: [
                                        {
                                                symbol: "calendar-check-o ",
                                                url: "*******"
                                        }
                                ]
                        } 
                        classes: "User1"
                },

I already used {} and "", ''. But I got the same error.
What did I wrong with this?
 
Thank you for your support anyway.

**Comment by thobbiit** [comment]
did you get a solution? I have the same problem

**Comment by wadewhitten** [comment]
@thobbiit @dennis100kr were either of you able to find the solution?
