### ISSUE TITLE
Slow facial recognition 

### ISSUE THREAD

**Issue by coltography** [normyx/MMM-Facial-Recognition-OCV3#2]
Hey, 

How can I speed up the facial recognition? Right now it takes about 5-6 seconds if I stand perfectly still.  
It seems to detect me as Stranger really quickly but then take a few seconds and then load my name/profile.

**Comment by normyx** [comment]
Hi,
Unfortunatly, it depends of the lights and the OpenCV algorithm. 
Try with the python tools.facialrecognition.py script to test.
You may change the play with interval and logoutDelay parameters (it will increase the cpu usage but decrease time to recognise).

**Comment by normyx** [comment]
Not an issue
