### ISSUE TITLE
Error while building Opencv - Please help if can!

### ISSUE THREAD

**Issue by ghost** [normyx/MMM-Facial-Recognition-OCV3#34]
I received this error while building opencv:

make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/build.make:128: modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:8811: modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

It was after entering "make -j4" in the command line.

There were a few red marked words before the code up here. Let me know if you would like to take a look.

**Comment by HorstBaerbel** [comment]
Yes, post the errors otherwise nobody will be able to help you. Also make sure you have all dependencies from the README installed, e.g.
```
sudo apt-get install libjpeg-dev libtiff5-dev libjasper-dev libpng12-dev
sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev libv4l-dev
```
Also read the [OpenCV installation guide](https://docs.opencv.org/3.4.9/d7/d9f/tutorial_linux_install.html).
