### ISSUE TITLE
other modules are not loading when MMM-facial-Recognition is added

### ISSUE THREAD

**Issue by nethajinirmal13** [normyx/MMM-Facial-Recognition-OCV3#5]
i just installed and added the facial recognition module in the config.js.
facial recognition is working fine but,other modules that have been added in config.js is not showing up

**Comment by E3V3A** [comment]
What does the logfiles say?
(And you're running this on RPi right?)

**Comment by normyx** [comment]
Hi,
Probably no `classes : ` tag in your config file.
