### ISSUE TITLE
Could not validate config file

### ISSUE THREAD

**Issue by Camerutttt** [normyx/MMM-Facial-Recognition-OCV3#7]
Hi, I have already done the capturing, training and testing of the model. Everything up to here works well. However, when I try to add the module to the config.js file and tried running the mirror, I received an error: "WARNING! Could not validate config file. Please correct syntax errors. Starting with default configuration." The mirror still launches, but I will get an error message of "Please create config file. See README for more information. If you get this message, while your config file is already corrected, your config file probably contains an error. Use a JavaScript linter to validate your file."

Only when I removed the MMM-Facial-Recognition-OCV3 module then the magic mirror runs as per normal.

**Comment by Camerutttt** [comment]
Heres the config file: 
```
{
    module: 'MMM-Facial-Recognition-OCV3',
    config: {
       threshold: 80,
       useUSBCam: false,        
       trainingFile: '/home/pi/MagicMirror/MMM-Facial-Recognition-OCV3/training.xml',        
       interval: 2,        
       logoutDelay: 15,        
       users: ["Dominic"],        
       defaultClass: "default",       
       everyoneClass: "everyone",         
        welcomeMessage: true
}
},
```

**Comment by Camerutttt** [comment]
My issue isn't solved.

**Comment by normyx** [comment]
Hi @Camerutttt 
Nothing seems wrong for this config. (except the trainingFile path, that need `modules`  i think). Did you install the module in `/home/pi/MagicMirror/modules/`. If it is not the case, it will not work well.
But it seems not to be an issue !

**Comment by christianmatei** [comment]
Same issue here, it think it requires more information on this error.
